/** Re-export mobile pairing storage helpers from the connection client. */
export {
  MOBILE_STORAGE_KEYS,
  clearPairingStorage,
  connectionHistoryId,
  readMobileConnectionHistory,
  readSessionToken,
  readStoredDeviceLabel,
  readStoredFingerprint,
  readStoredHostBase,
  rememberMobileConnection,
  removeMobileConnectionHistory,
  resolveDefaultDeviceLabel,
  resolveDeviceLabel,
  touchMobileConnectionHistory,
  writePairingResult,
  writeStoredDeviceLabel,
  writeStoredHostBase,
  type SavedMobileConnection,
} from '@deepseek-ai/dsh-client-connection/client'
